---

runs:
  using: "composite"
  steps:
    - name: Install PIP modules
      id: install-pip-modules
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt --upgrade --upgrade-strategy eager

# vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
